### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by lemairecarl** [kuangliu/pytorch-ssd#6]
This repo is the best PyTorch SSD implementation I've found. I've adapted the code to my needs. Some parts changed a lot, some parts remained.

I suggest you consider adding a permissive open-source license to your repo. (["No License" is pretty restrictive.](https://choosealicense.com/no-permission/)) Good choices:

* [Unlicense](https://choosealicense.com/licenses/unlicense/)
* [MIT License](https://choosealicense.com/licenses/mit/)

[See other choices here.](https://choosealicense.com/)

[Here's how to add a license to a GitHub repo.](https://help.github.com/articles/adding-a-license-to-a-repository/)

**Comment by kuangliu** [comment]
MIT license is added. 

Note this implementation has some bugs I haven't fixed. Checkout my newer SSD implementation in [torchcv](https://github.com/kuangliu/torchcv), which is bug free and well evaluated.

If you prefer the concise structure this code has, I encourage you to compare the two versions carefully.

**Comment by lemairecarl** [comment]
Thanks!

Yes, I had to fix many things and upgrade to PyTorch 0.3. But it works. I'm not getting the performance I expect but I'm going to try modifying the data augmentation. I'll take a look at your new repo.
