### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by Toory465** [kuangliu/pytorch-ssd#8]
Hi, 
Thanks for the code. I just tried to use training data in the following link
"http://host.robots.ox.ac.uk/pascal/VOC/voc2012/index.html".

However I will keep getting this error : 
**The expanded size of the tensor (512) must match the existing size (32) at non-singleton dimension 1.**

Maybe I am using the wrong dataset. Could you please let me know how to fix it.
Thanks

**Comment by kuangliu** [comment]
Use [torchcv](https://github.com/kuangliu/torchcv).
